name: Deploy Portfolio (CRA + Next.js) to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (CRA root)
        run: npm ci

      - name: Build CRA
        run: npm run build

      - name: Install deps (Next.js)
        working-directory: portfolio-nextjs
        run: npm ci

      - name: Build Next.js (static export)
        working-directory: portfolio-nextjs
        env:
          GITHUB_PAGES: 'true'
        run: npm run build

      - name: Combine artifacts
        run: |
          mkdir -p build/portfolio-nextjs
          if [ -d portfolio-nextjs/out ]; then
            # Copy all files including dotfiles (e.g., .nojekyll)
            cp -R portfolio-nextjs/out/. build/portfolio-nextjs/
          else
            echo "Error: Next.js export directory 'portfolio-nextjs/out' not found."
            echo "Ensure the previous build step succeeded and produced a static export."
            exit 1
          fi
          touch build/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
